# Generated by Django 5.1.5 on 2025-02-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_details', models.TextField()),
                ('closing_date', models.DateField()),
                ('qualifications', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('pay_details', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], default='FT', max_length=2)),
            ],
        ),
    ]
