# Generated by Django 5.1.5 on 2025-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr', '0002_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
