# Generated by Django 5.1.5 on 2025-02-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epr', '0006_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
